alter session set "_ORACLE_SCRIPT"=true;
create user c##devtest identified by "devtestpassword";
select user from dual;
grant all privileges to c##devtest;

create table c##devtest.table_one(
    id number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_first number
);

create table table_two(
    id number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_second number,
    constraint fk_field_one_id foreign key(field_second) references table_one(id)
);

alter table table_one
add constraint fk_field_two  foreign key(field_first) references table_two(field_second);

