alter session set "_ORACLE_SCRIPT"=true;
create user c##dev identified by "devpassword";
select user from dual;
grant all privileges to c##dev;

create table table_one(
    id number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_first number
);

create table table_two(
    id number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_second number,
    constraint fk_field_one_id foreign key(field_second) references table_one(id)
);
create table c##prod.
alter table table_one
add constraint fk_field_two  foreign key(field_first) references table_two(field_second);

