alter session set "_ORACLE_SCRIPT"=true;
create user c##prod identified by "prodpassword";
grant all privileges to c##prod;

create table c##prod.table_one(
    id number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_first number
);

create table c##prod.table_two(
    id number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_first number
);
drop table table_two;
create index first_index on table_one(field_first);