alter session set "_ORACLE_SCRIPT"=true;
create user c##prod identified by "prodpassword";
grant all privileges to c##prod;

create table c##dev.table_one(
    id number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_first number
);